name = "xflexacademy"
pages_build_output_dir = "dist/public"

[env.production]
name = "xflexacademy-prod"
routes = [
  { pattern = "xflexacademy.com/*", zone_name = "xflexacademy.com" },
  { pattern = "www.xflexacademy.com/*", zone_name = "xflexacademy.com" }
]

[env.preview]
name = "xflexacademy-preview"
